### ISSUE TITLE
How can I help? 

### ISSUE THREAD

**Issue by 6abotage** [ibelick/motion-primitives#1]
Hey there! 👋
I stumbled upon your motion primitives library in the weekly React newsletter and it's got me stoked! This looks like it could be a game-changer for Framer Motion devs.

I'm itching to contribute. Do you need any help with the project right now?

Some suggestions:
- Since it's open source and the repository should be easy to set-up with the right extensions on everyone's machine you could add recommended extensions like MDX, Tailwind etc.
https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions
- Add prettier with tailwind class sorting
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

**Comment by ibelick** [comment]
Thanks for the suggestions! I’ve just added prettier with `prettier-plugin-tailwindcss`. Right now, I’m focused on expanding the component collection and defining more patterns. Your help with these would be invaluable. We should also consider adding a CONTRIBUTING.md to guide new contributors.

**Comment by pilladipesh33** [comment]
I'm interested too, count me in.

**Comment by gabe-santos** [comment]
Same here! Anything I can do to help?

**Comment by ibelick** [comment]
@gabe-santos Yes! Right now, I'm focusing on expading the core component collection, but i'm open to any other areas where you think you can contribute :)

**Comment by gabe-santos** [comment]
Do you have a roadmap of features?

**Comment by Aakash-Sondagar** [comment]
I am interested in contributing to this library; is there anything I can do to help?

**Comment by Amumug** [comment]
Me too is there anything to help you?

**Comment by MathPow** [comment]
Same here! :)

**Comment by zerofcs** [comment]
Lmk as well! :3

**Comment by auronvila** [comment]
I can contribute too, the animations are stunning, I had an idea to create something like this but luckily I came across and why not make it better? The data table components are very hard to build but there are not many samples about animating the data table maybe if we can figure this out would take us ahead?

**Comment by no-naame** [comment]
yeah , the work seems promising , I would also like to contribute and learn.

**Comment by deiondz** [comment]
Seems like a dope library. Would love to contribute as well.

**Comment by ibelick** [comment]
Hey everyone, I've just started a discussion to exchange ideas for new components or improvements
https://github.com/ibelick/motion-primitives/discussions/24

**Comment by sheikhmubashi** [comment]
Just discovered this library—it seems like a game changer for the future. I'm really excited to contribute!

**Comment by ibelick** [comment]
I close the issue. You can help by creating a new issue with a component idea, checking open issues where help is needed, or contributing in any other way to expand the project. Feel free to DM / email me if you have any ideas. Thank you!
