### ISSUE TITLE
Dialog component useClickOutside hook seems to be missing

### ISSUE THREAD

**Issue by Saltys-Git** [ibelick/motion-primitives#28]
In the code of the dialog component, there is an import named "useClickOutside" from '@/hooks/useClickOutside' and the code for the hook is not mentioned somewhere on the dialog page.

**Comment by phoskee** [comment]
The useClickOutside hook, which is used in the dialog component, can be found in the repository at hooks/useClickOutside.tsx.
```tsx
import { RefObject, useEffect } from 'react';

function useClickOutside<T extends HTMLElement>(
  ref: RefObject<T>,
  handler: (event: MouseEvent | TouchEvent) => void
): void {
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent | TouchEvent) => {
      if (!ref || !ref.current || ref.current.contains(event.target as Node)) {
        return;
      }

      handler(event);
    };

    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('touchstart', handleClickOutside);

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('touchstart', handleClickOutside);
    };
  }, [ref, handler]);
}

export default useClickOutside;
```

**Comment by kentntwari** [comment]
@phoskee it would be great if the hook could be included in the docs for added clarity. The first thing that comes to mind right before using the component is that some things are missing therefore there's an issue with the component itself when it's truly not.

**Comment by ibelick** [comment]
[Fixed!](https://github.com/ibelick/motion-primitives/commit/8f0ed075968ea244fda54d2c717b1a2d3645f927)
