### ISSUE TITLE
Collapsable Input Component Text Color Not Visible in Dark Theme

### ISSUE THREAD

**Issue by sheikhmubashi** [ibelick/motion-primitives#29]
The dynamic toolbar component has a text visibility issue in dark theme. The text isn't visible inside the input field, though it works fine in light theme.

Steps to Reproduce:

Switch to dark theme.
Use the Collapsable Input component.
Type in the input field.
Expected Behavior:
Text should be visible in both themes.

Actual Behavior:
Text is not visible in the dark theme.

[Attaching a video for reference.](https://www.loom.com/share/78ac744e45ac4ef4a2d7a41d4b48adc9?sid=5036f15f-aad8-4e82-990d-b64a82facf88)

**Comment by ibelick** [comment]
Thanks, its [fixed](https://github.com/ibelick/motion-primitives/commit/0ef4f089bd77a0d8179f209264f2a1f7e2e614d8)!
