### ISSUE TITLE
[Bug] Props Overwritten in AccordionItem Component

### ISSUE THREAD

**Issue by kashyap20** [ibelick/motion-primitives#33]
# Description:
The `AccordionTrigger` and `AccordionContent` components expose the `expanded` and `onToggle` props, allowing users to control the state of the accordion externally. However, these props are not functioning as expected because they are being overridden within the `AccordionItem` component.

Affected Components:
- AccordionTrigger
- AccordionContent
- AccordionItem

## Code Example:

``` typescript
// AccordionTriggerProps
type AccordionTriggerProps = {
  children: ReactNode;
  className?: string;
  onToggle?: () => void;
  expanded?: boolean;
};

// AccordionContentProps
type AccordionContentProps = {
  children: ReactNode;
  expanded?: boolean;
  className?: string;
};
```

### AccordionItem Code:

```typescript
{React.Children.map(children, (child) =>
  React.cloneElement(child as React.ReactElement<any>, {
    expanded: isExpanded,
    onToggle: () => toggleItem(value),
  })
)}
```

## Issue:
In the `AccordionItem` component, the `expanded` and `onToggle` props passed down to `AccordionTrigger` and `AccordionContent` are being overwritten by the values generated within `AccordionItem`. Making the externally passed values ineffective.

## Expected Behavior:
The `expanded` and `onToggle` props should work as intended, allowing external control over the accordion state. The internal logic in `AccordionItem` should not override these props unless they are not provided.

## Steps to Reproduce:
Pass `expanded` and `onToggle` props to `AccordionTrigger` and `AccordionContent`.
Observe that these props are ignored, and the internal state of `AccordionItem` is used instead.

**Comment by timurbesli** [comment]
Yep, ontoggle doesnt work.

**Comment by ibelick** [comment]
Fixed https://github.com/ibelick/motion-primitives/pull/38

You can now use `expandedValue` and `onValueChange` in `<Accordion />`.
