### ISSUE TITLE
Open a public Figma project

### ISSUE THREAD

**Issue by MathPow** [ibelick/motion-primitives#8]
### Context
To enhance collaboration and streamline the design-to-development process, I propose opening a public Figma project for the components. This will allow for transparent and real-time design updates, fostering better communication between developers.

### Tasks List
1. Create a public Figm a project.
2. Add a page for a design sytem and a page per component.
3. Write a doc page to explained the structure, guidelines and goals of a Figma designs.
4. Share the new link with the team.

**Comment by DeepakKumarKhatri** [comment]
@MathPow this would be helpful for all contributors. Great idea.

**Comment by dannylnz** [comment]
Hey! I am working on it. Using the shadcn base to build a skeleton of the figma.
Current challenges:
- primitives are very different between them, so for now, until we find some patterns we have to create the full component without master primitives
- the colors in css are using a convention that is hard to translate in a design system (IE: for borders you're using color/10, which in hex is another color, and we can't have a common palette unless we start to use a common pattern in code.)

**Comment by MathPow** [comment]
Great! Could you share the link here when it will be done?

**Comment by dannylnz** [comment]
here the link of the very first version
https://www.figma.com/community/file/1405137831253908116/motion-primitives-design-library

**Comment by ibelick** [comment]
Thanks for the contribution! Since the project is focused on animated components, maintaining this Figma file might be tricky. Setting up basic UI rules could help. I'll keep the idea in mind!
