### ISSUE TITLE
Add a roadmap section to the READ.ME file

### ISSUE THREAD

**Issue by MathPow** [ibelick/motion-primitives#9]
### Context

The roadmap serves as a living document that evolves with the project, allowing teams to plan for new components. Using a roadmap help align development efforts with broader project goals. It would be helpful to have something like this so new developers who want to contribute can see what tasks they could work on.

**Comment by jsaumap** [comment]
it would be nice to have one. If you want to someone else create it, provide a minimal list with the components that you have on mind

**Comment by MathPow** [comment]
I don't know what the owner of the repo had in mind. Maybe a GitHub discussion would help this cause. How do we open one?

**Comment by okunamayanad** [comment]
It would be nicer to have it on a [GitHub Project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) instead

**Comment by ZipBrandon** [comment]
> I don't know what the owner of the repo had in mind. Maybe a GitHub discussion would help this cause. How do we open one?

Glad to see Discussions brought up.  The CONTRIBUTING.md mentions bringing up discussions but it does not appear to be turned on. If @ibelick can do so then that would stave off of a lot of wasted efforts and duplicated efforts. This repo has gotten a lot of interest recently and that comes with the good and the bad. I'm merely an observer to this but I wonder if just opening unsolicited and undiscussed PRs is in the correct direction for @ibelick's vision for the library.  I believe [this PR](https://github.com/ibelick/motion-primitives/pull/5) is well-intentioned but ensure that it meets the expectations of @ibelick. Is @ibelick comfortable with Figma? Sure, https://github.com/ibelick/motion-primitives/issues/8 is a great idea but the project (or acommitted contributor) needs to be comfortable with Figma and keeping the components maintained so it does not diverge and go stale. 

In similar vain, I see a lot of hands that want to help flesh out this library but I'm personally wary of the quality of component that could be delivered by someone who isn't as rigorous and adept as @ibelick. To that point, check out [his lab](https://ibelick.com/lab)! Those are some terrific experiments in UI that might-or-might-not stick. 

I'm not trying to be a naysayer or wet blanket. I see the excitement. Let's just be sure that we aren't trying to be Armchair Project Managers for @ibelick's creation and potentially ruin a pretty great thing.

**Comment by ibelick** [comment]
I don’t plan a roadmap, I’m closing the issue. Thanks!
