### ISSUE TITLE
Error: usePreventScroll Component Not Found When Installing Morphing Dialog

### ISSUE THREAD

**Issue by Acadbek** [ibelick/motion-primitives#90]
When trying to install the Morphing Dialog component, I encountered the following error:

`Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

The component at https://ui.shadcn.com/r/styles/default/hooks/usePreventScroll.json was not found.
It may not exist at the registry. Please make sure it is a valid component.
`

Steps to Reproduce:

1. Open the terminal.
2. Run the following command:

`npx shadcn add "https://motion-primitives.com/c/morphing-dialog.json" "https://motion-primitives.com/h/useClickOutside.json"
`
3. Observe the error mentioned above.

Expected Behavior:
The Morphing Dialog component should install successfully without errors.

Actual Behavior:
The installation fails with an error message stating that the usePreventScroll component could not be found in the registry.

System Information:

OS: Windows 10
Node.js Version: v20.17.0
React Version: ^18.3.1

**Comment by ibelick** [comment]
Fixed https://github.com/ibelick/motion-primitives/commit/612de37e51bb0a1f26c1e45bfd30bd73ce2926f6
